# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.10

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

before_script:
  - python --version  # For debugging
  - pip install --upgrade pip
  - pip install -r step/requirements.txt
  - pip install -r step/requirements-dev.txt

stages:
  - testing
  - build
  - deploy

django-tests:
  stage: testing
  script:
    - cd step
    - python manage.py migrate
    - python manage.py test
    - echo "Testing has completed"

lint:
  stage: testing
  script:
    - pylint $(git ls-files '*.py')
    - echo "Checking by linter has completed"

make_build:
  stage: build
  script:
    - echo "Building has completed"

deploy:
  stage: deploy
  script:
    - echo "Deploying has completed"
  environment: production

