# Generated by Django 4.1.6 on 2023-02-09 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(editable=False, max_length=256, verbose_name='Наименование курса/Course name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О курсе/Description')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=1, editable=False, max_digits=100, verbose_name='Процент прохождения/Completion percent')),
                ('test_result', models.BooleanField(default=False, editable=False, verbose_name='Статус теста/Test status')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stafftrain.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
