# Generated by Django 4.1.6 on 2023-02-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stafftrain', '0002_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доступен/Available'),
        ),
    ]
